---
title: "big five"
author: "yiren"
date: "08/11/2021"
output: html_document
---

```{r setup, include=FALSE}
library(gtsummary)
library(dplyr)
require(d3heatmap, lib.loc ="/Users/yirencao/Desktop")
df = read.csv("2015_for_r.csv") %>% select(c(87:121, 123, 134)) 
df["year"] = 2015

for(i in 2016:2020) { 
 temp <- read.csv(paste( i, "_for_r.csv", sep = ""))  %>% select(c(87:121, 123, 134)) 
 temp["year"] = i
 df <- rbind(df, temp)
}

trump <- df %>% filter(itemLabel == "Donald Trump")
# Joe Biden, #Donald Trump, #Barack Obama, 5 personality
```

```{r}
library(ggplot2)
# convert wide to long
library(tidyr)

# Trump
long <- trump %>% gather(personality, value, -c(itemLabel, party, year))
p1 = ggplot(long, aes(x=year, y = value, colour = personality)) +  geom_line()
library(plotly)
ggplotly(p1)

```

```{r}
# # Bernie Sanders
# Sanders <- df %>% filter(itemLabel == "Bernie Sanders")
# long <- Sanders %>% gather(personality, value, -c(itemLabel, party, year))
# p4 = ggplot(long, aes(x=year, y = value, colour = personality)) +  geom_line()
# ggplotly(p4)
```


```{r}
# Biden
biden <- df %>% filter(itemLabel == "Joe Biden")
long <- biden %>% gather(personality, value, -c(itemLabel, party, year))
p2 = ggplot(long, aes(x=year, y = value, colour = personality)) +  geom_line()
ggplotly(p2)

```


```{r}
# # Hillary
# hillary <- df %>% filter(itemLabel == "Hillary Clinton")
# long <- hillary %>% gather(personality, value, -c(itemLabel, party, year))
# p3 = ggplot(long, aes(x=year, y = value, colour = personality)) +  geom_line()
# ggplotly(p3)
```


```{r}
# 
obama <- df %>% filter(itemLabel == "Barack Obama")
long <- obama %>% gather(personality, value, -c(itemLabel, party, year))
p5 = ggplot(long, aes(x=year, y = value, colour = personality)) +  geom_line()
ggplotly(p5)
```


```{r}
# Graham <- df %>% filter(itemLabel == "Lindsey Graham")
# long <- Graham %>% gather(personality, value, -c(itemLabel, party, year))
# p6 = ggplot(long, aes(x=year, y = value, colour = personality)) +  geom_line()
# ggplotly(p6)
```


```{r}
only_five <- df %>% select(neuroticism, extraversion, agreeableness, conscientiousness, openness, year, itemLabel) 
only_five_long <- only_five %>%  gather(personality, value, -c(itemLabel, year)) %>% filter(itemLabel %in% c("Barack Obama", "Hillary Clinton", "Joe Biden", "Elizabeth Warren", "Andrew Cuomo", "Donald Trump", "Lindsey Graham", "George W. Bush","Bernie Sanders"))

ggplot(only_five_long, aes(x=year, y = value, colour = personality)) +  geom_line() + facet_wrap(~itemLabel)

# only_five %>% filter(itemLabel == "Bernie Sanders")

```

```{r}
only_five <- df %>% select(neuroticism, extraversion, agreeableness, conscientiousness, openness, year, itemLabel) 
only_five_long <- only_five %>%  gather(personality, value, -c(itemLabel, year)) %>% filter(itemLabel %in% c("Barack Obama", "Hillary Clinton", "Joe Biden", "Elizabeth Warren", "Andrew Cuomo", "Donald Trump", "Lindsey Graham", "George W. Bush","Bernie Sanders"))
# 
# ggplot(only_five_long, aes(x=year, y = value, colour = personality)) +  geom_line() + facet_wrap(~itemLabel)
# 
# 
# ggplot(
#   only_five_long,
#   aes(year, value, group = personality, color = personality)
# ) +
#   geom_line() +
#   scale_color_viridis_d() +
#   labs(x = "year", y = "value") +
#   theme(legend.position = "top")


pca_arrests = princomp(df1)
# install.packages("remotes")
# remotes::install_github("vqv/ggbiplot")
library(ggbiplot)
p1 = ggscreeplot(pca_arrests) +
  theme_bw(base_size = 20) + labs(y = "Prop. of explained variance")
p2 = ggscreeplot(pca_arrests,type = "cev") + theme_bw(base_size = 20) + labs(y = " Cumulative prop. of explained variance")
gridExtra::grid.arrange(p1, p2, ncol=2)


ggbiplot(pca_arrests, labels =  rownames(df1), labels.size = 3, varname.size = 5) +
  theme_bw(base_size = 20) + coord_cartesian(ylim = c(-2.5,2.5), xlim = c(-2.5,2.5))

set.seed(1)
cl_arrests = kmeans(df1, centers = 4, nstart = 10)
p = ggbiplot(
  pca_arrests,
  groups = factor(cl_arrests$cluster),
  labels =  rownames(df1),
  ellipse = TRUE) + 
  theme_bw(base_size = 20) +
  theme(legend.position = "none")
p
df1$cluster = cl_arrests$cluster
df_cluster = df1 %>% dplyr::select(cluster)
summary(cl_arrests$cluster)
df_cluster$pickup_community_area = rownames(df_cluster)
rownames(df_cluster) = 1:77


 
```



```{r, include=FALSE}
# sample_gally <- df %>% dplyr::select(N, E, O, A, C, party)
# GGally::ggpairs(sample_gally, mapping=ggplot2::aes(colour = party),
#   lower=list(combo=wrap("facethist",binwidth=1))) + theme_bw(base_size = 22)
```

```{r, include = FALSE, warning=FALSE}
df1 <- df %>% select(c(87:121, 123, 134)) # 87:121 contains all personalities, 123 is name, 134 is party

df_personality <-  df %>% select(c(87:121))
# df_personality %>% tbl_summary()
```

```{r, echo =FALSE, warning = FALSE}
df_personality_party <-  df %>% select(c(87:121, 134))
df_output = df_personality_party %>% tbl_summary(by = party) %>% add_p()

```


```{r, echo = FALSE}
df2 <- df %>% select(c(123, 87:121))
rownames(df2) <- df2$itemLabel
df2 <- df2 %>% select(-itemLabel)
# heatmap(as.matrix(df2))


```


```{r, echo = FALSE}
# library(d3heatmap)
df_several <- df2[c("Barack Obama", "Hillary Clinton", "Joe Biden", "Elizabeth Warren", "Andrew Cuomo", "Donald Trump", "Lindsey Graham", "George W. Bush"),]
d3heatmap(scale(df_several), colors = "RdYlBu",
          k_row = 4, # Number of groups in rows
          k_col = 2, # Number of groups in columns
          scale = "column"
          )
```


```{r}

heatmap_whole <- d3heatmap(scale(df2), colors = "RdYlBu",
          k_row = 4, # Number of groups in rows
          k_col = 2, # Number of groups in columns
          scale = "column"
          )
```


```{r}
# df_person <- df %>%
#   filter(itemLabel %in% c("Donald Trump", "Barack Obama")) 
# 
# persons <- c("Donald Trump", "Barack Obama")
# personality <- c(1, 2, 3, 4, 5)
# trump <- c(0.015382638,	0.02964612,	-0.07001895,	0.05538805,	-0.01703972	)
# obama <- c(0.009082505,	0.03680336,	-0.06844304,	0.06290123,	-0.01105373)
# data <- data.frame( time, trump, obama)
# data  %>%
#   ggplot(aes(x=personality)) + 
#   geom_line(aes(y = trump), color = "darkred") + geom_line(aes(y = obama), color="steelblue") 

```







```{r}
# df2 = read.csv("df2")
# df_person <- df2 %>%
#   filter(itemLabel %in% c("Donald Trump", "Barack Obama", "Joe Biden", "Hillary Clinton")) 
```
```{r}
# summary(df2)

# (-1,1), (0, 100)
#use all politicians as the baseline
# (value-min)/diff * 100
# use longer quotes
```



```{r}
# df_person %>% filter
# 
# persons <- c("Donald Trump", "Barack Obama")
# personality <- c(1, 2, 3, 4, 5)
# trump <- c(0.015382638,	0.02964612,	-0.07001895,	0.05538805,	-0.01703972	)
# obama <- c(0.009082505,	0.03680336,	-0.06844304,	0.06290123,	-0.01105373)
# data <- data.frame(time, trump, obama)
# data  %>%
#   ggplot(aes(x=personality)) + 
#   geom_line(aes(y = trump), color = "darkred") + geom_line(aes(y = obama), color="steelblue") 

```





